# Generated by Django 4.2.10 on 2024-04-12 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wordapp", "0004_achievement_userachievement_studyprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studyprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
